-- NOTE: WELCOMEi
-- TODO: This is work
require("user.options")
require("user.keymaps")
require("user.autocommands")
require("user.lazy")
require("user.colorscheme")
require("user.telescope")
require("user.nvimtree")
require("user.treesitter")
require("user.lsp")
require("user.comment")
require("user.auto-tag")
require("user.luasnip")
require("user.lualine")
require("user.bufferline")
require("user.js-doc")
-- require("user.conform")
-- require("user.vim-prettier")
require("user.nvim-cmp")
-- TODO: I LOVE NVIM
