-- require("lspconfig").ts_ls.setup({
-- 	on_attach = function(client, bufnr)
-- 		require("workspace-diagnostics").populate_workspace_diagnostics(client, bufnr)
-- 	end,
-- })

-- vim.lsp.config("ts_ls")({
-- 	on_attach = function(client, bufnr)
-- 		require("workspace-diagnostics").populate_workspace_diagnostics(client, bufnr)
-- 	end,
-- })
